<?php
    
    
    $wordlist = array(
        'setel/a.php','setelan/','plugins/','application','template','images/','js/','form_edit','bootstrap/','dist/','cbt'
        ,'adminpannel/img/','adminpanel/login.php','systemadmin/','administrator/','admin1/','admin2/','admin3/','admin4/','admin5/','usuarios/',
    'usuario/','administrator/','moderator/','webadmin/','adminarea/','bb-admin/','adminLogin/','admin_area/',
    'panel-administracion/','instadmin/','memberadmin/','systemadmin','adm/','admin/account.php',
    'admin/index.php','admin/login.php','admin/admin.php','admin/account.php','admin_area/admin.php',
    'admin_area/login.php','siteadmin/login.php','siteadmin/index.php','siteadmin/login.html','admin/account.html',
    'admin/index.html','admin/login.html','admin/admin.html','admin_area/index.php','bb-admin/index.php','bb-admin/login.php',
    'bb-admin/admin.php','admin/home.php','admin_area/login.html','admin_area/index.html','admin/controlpanel.php','admin.php',
    'admincp/index.asp','admincp/login.asp','admincp/index.html','admin/account.html','adminpanel.html','webadmin.html',
    'webadmin/index.html','webadmin/admin.html','webadmin/login.html','admin/admin_login.html','admin_login.html',
    'panel-administracion/login.html','admin/cp.php','cp.php','administrator/index.php','administrator/login.php',
    'nsw/admin/login.php','webadmin/login.php','admin/admin_login.php','admin_login.php','administrator/account.php',
    'administrator.php','admin_area/admin.html','pages/admin/admin-login.php','admin/admin-login.php','admin-login.php',
    'bb-admin/index.html','bb-admin/login.html','acceso.php','bb-admin/admin.html','admin/home.html',
    'login.php','modelsearch/login.php','moderator.php','moderator/login.php','moderator/admin.php','account.php',
    'pages/admin/admin-login.html','admin/admin-login.html','admin-login.html','controlpanel.php','admincontrol.php',
    'admin/adminLogin.html','adminLogin.html','admin/adminLogin.html','home.html','rcjakar/admin/login.php',
    'adminarea/index.html','adminarea/admin.html','webadmin.php','webadmin/index.php','webadmin/admin.php',
    'admin/controlpanel.html','admin.html','supermanasp','cp.html','adminpanel.php','moderator.html',
    'administrator/index.html','administrator/login.html','user.html','administrator/account.html','administrator.html',
    'login.html','modelsearch/login.html','moderator/login.html','adminarea/login.html','panel-administracion/index.html',
    'panel-administracion/admin.html','modelsearch/index.html','modelsearch/admin.html','admincontrol/login.html',
    'adm/index.html','adm.html','moderator/admin.html','user.php','account.html','controlpanel.html','admincontrol.html',
    'panel-administracion/login.php','wp-login.php','adminLogin.php','admin/adminLogin.php','home.php','admin.php',
    'adminarea/index.php','adminarea/admin.php','adminarea/login.php','panel-administracion/index.php',
    'panel-administracion/admin.php','modelsearch/index.php','modelsearch/admin.php','admincontrol/login.php',
    'adm/admloginuser.php','admloginuser.php','admin2.php','admin2/login.php','admin2/index.php','usuarios/login.php',
    'adm/index.php','adm.php','affiliate.php','adm_auth.php','memberadmin.php','administratorlogin.php','admin.asp','admin/admin.asp',
    'admin_area/admin.asp','admin_area/login.asp','admin_area/index.asp','bb-admin/index.asp','bb-admin/login.asp',
    'bb-admin/admin.asp','pages/admin/admin-login.asp','admin/admin-login.asp','admin-login.asp','user.asp','webadmin/index.asp',
    'webadmin/admin.asp','webadmin/login.asp','admin/admin_login.asp','admin_login.asp','panel-administracion/login.asp',
    'adminLogin.asp','admin/adminLogin.asp','home.asp','adminarea/index.asp','adminarea/admin.asp','adminarea/login.asp',
    'panel-administracion/index.asp','panel-administracion/admin.asp','modelsearch/index.asp','modelsearch/admin.asp',
    'admincontrol/login.asp','adm/admloginuser.asp','admloginuser.asp','admin2/login.asp','admin2/index.asp','adm/index.asp',
    'adm.asp','affiliate.asp','adm_auth.asp','memberadmin.asp','administratorlogin.asp','siteadmin/login.asp','siteadmin/index.asp',
    'madspot.php','mad.php','404.php','anon.php','anonymous.php','shell.php','sh3ll.php',
    'madspotshell.php','b374k.php','c100.php','priv8.php','private.php','cp.php','cpbrute.php','themes/404/404.php',
    'templates/atomic/index.php','templates/beez5/index.php','hacked.php','r57.php','wso.php','WSO.php','wso24.php',
    'wso26.php','wso404.php','sym.php','symsa2.php','sym3.php','whmcs.php','whmcskiller.php','cracker.php','1.php','2.php',
    'sql.php','gaza.php','database.php','a.php','d.php','dz.php','cpanel.php','system.php','um3r.php','zone-h.php','c22.php',
    'root.php','r00t.php','doom.php','dam.php','killer.php','user.php','wp-content/plugins/disqus-comment-system/disqus.php',
    'cpn.php','shelled.php','uploader.php','up.php','xd.php','d00.php','h4xor.php','tmp/mad.php','tmp/1.php',
    'wp-content/plugins/akismet/akismet.php','images/stories/w.php','w.php','downloads/dom.php','templates/ja-helio-farsi/index.php','wp-admin/m4d.php',
    'd.php','wp-content/uploads/2021/01/12.php','wp-content/uploads/2021/02/12.php','wp-content/uploads/2021/03/12.php',
    'wp-content/uploads/2021/04/12.php','wp-content/uploads/2021/05/12.php','wp-content/uploads/2021/06/12.php',
    'wp-content/uploads/2021/07/12.php','wp-content/uploads/2021/08/12.php','wp-content/uploads/2021/09/12.php',
    'wp-content/uploads/2021/10/12.php','wp-content/uploads/2021/11/12.php','wp-content/uploads/2021/12/12.php','0admin/','0manager/','aadmin/','acceso.','acceso.asp','acceso.brf','acceso.cfm',
'acceso.cgi','acceso.%EXT%','acceso.js','acceso.php','access/','access.','access.%EXT%','account.asp','account.brf','account.cfm','account.cgi','account.html','account.js','account.php',
'accounts/','accounts.','accounts.%EXT%','acct_login/','acesso/','adimin/','adiministrador/','adm',
'adm/','adm.','adm/admin/','adm/admloginuser.asp','adm/admloginuser.brf','adm/admloginuser.cfm',
'adm/admloginuser.cgi','adm/admloginuser.js','adm/admloginuser.php','adm.asp','adm_auth.',
'adm_auth.asp','adm_auth.brf','adm_auth.cfm','adm_auth.cgi','adm_auth.%EXT%','adm_auth.js',
'adm_auth.php','adm.brf','adm.cfm','adm.cgi','admcp','adm.%EXT%','adm.html','admin','admin/',
'admin.','ADMIN/','admin1/','admin1.','admin1.asp','admin1.%EXT%','admin1.htm','admin1.html',
'admin1.php','admin2/','admin2.','admin2.asp','admin2.brf','admin2.cfm','admin2.cgi','admin2.%EXT%',
'admin2.html','admin2/index.asp','admin2/index.brf','admin2/index.cfm','admin2/index.cgi',
'admin2/index.js','admin2/index.php','admin2.js','admin2/login.asp','admin2/login.brf',
'admin2/login.cfm','admin2/login.cgi','admin2/login.js','admin2/login.php','admin2.php','admin3/',
'admin4/','admin4_account/','admin4_colon/','admin5/','admin/account.','admin/account.asp',
'admin/account.brf','admin/account.cfm','admin/account.cgi','admin/account.%EXT%','admin/account.html','admin/account.js','admin/account.php','admin/adm/','admin/admin/','admin/admin.',
'admin/admin.asp','admin/admin.brf','admin/admin.cfm','admin/admin.cgi','admin/admin.%EXT%',
'admin/admin.html','admin/admin.js','admin/admin_login.','admin/admin-login.','admin/adminLogin.',
'admin/admin_login.asp','admin/admin-login.asp','admin/adminLogin.asp','admin/admin_login.brf',
'admin/admin-login.brf','admin/adminLogin.brf','admin/admin_login.cfm','admin/admin-login.cfm',
'admin/adminLogin.cfm','admin/admin_login.cgi','admin/admin-login.cgi','admin/adminLogin.cgi',
'admin/admin_login.%EXT%','admin/admin-login.%EXT%','admin/adminLogin.%EXT%','admin/adminLogin.htm',
'admin/admin_login.html','admin/admin-login.html','admin/adminLogin.html','admin/admin_login.js',
'admin/admin-login.js','admin/adminLogin.js','admin/admin_login.php','admin/admin-login.php',
'admin/adminLogin.php','admin/admin.php','adminare','admin_area/','admin_area.','adminarea/',
'admin_area/admin.','admin_area/admin.asp','adminarea/admin.asp','admin_area/admin.brf',
'adminarea/admin.brf','admin_area/admin.cfm','adminarea/admin.cfm','admin_area/admin.cgi',
'adminarea/admin.cgi','admin_area/admin.%EXT%','admin_area/admin.html','adminarea/admin.html',
'admin_area/admin.js','adminarea/admin.js','admin_area/admin.php','adminarea/admin.php',
'admin_area.%EXT%','admin_area/index.asp','adminarea/index.asp','admin_area/index.brf',
'adminarea/index.brf','admin_area/index.cfm','adminarea/index.cfm','admin_area/index.cgi',
'adminarea/index.cgi','admin_area/index.html','adminarea/index.html','admin_area/index.js',
'adminarea/index.js','admin_area/index.php','adminarea/index.php','admin_area/login.asp',
'adminarea/login.asp','admin_area/login.brf','adminarea/login.brf','admin_area/login.cfm',
'adminarea/login.cfm','admin_area/login.cgi','adminarea/login.cgi','admin_area/login.%EXT%',
'admin_area/login.html','adminarea/login.html','admin_area/login.js','adminarea/login.js',
'admin_area/login.php','adminarea/login.php','admin.brf','admin.cfm','admin.cgi','admincontrol/',
'admincontrol.','admincontrol.asp','admincontrol.brf','admincontrol.cfm','admincontrol.cgi',
'admincontrol.%EXT%','admincontrol.html','admincontrol.js','admincontrol/login.asp',
'admincontrol/login.brf','admincontrol/login.cfm','admincontrol/login.cgi','admincontrol/login.html',
'admincontrol/login.js','admincontrol/login.php','admin/controlpanel.','admin/controlpanel.asp',
'admin/controlpanel.brf','admin/controlpanel.cfm','admin/controlpanel.cgi','admin/controlpanel.%EXT%','admin/controlpanel.htm','admin/controlpanel.html','admin/controlpanel.js','admin/controlpanel.php','admincontrol.php','admincp','admin/cp'.'admincp','admincp/','admin/cp.asp',
'admin/cp.brf','admin/cp.cfm','admin/cp.cgi','admin/cp.%EXT%','admin/cp.html','admincp/index.asp',
'admincp/index.html','admin/cp.js','admincp/login.','admincp/login.asp','admincp/login.%EXT%',
'admin/cp.php','adm/index.asp','adm/index.brf','adm/index.cfm','adm/index.cgi','adm/index.html',
'adm/index.js','adm/index.php','admin.%EXT%','admin/home.','admin/home.asp','admin/home.brf',
'admin/home.cfm','admin/home.cgi','admin/home.%EXT%','admin/home.html','admin/home.js','admin/home.php','admin.htm','admin.html','admin/index.asp','admin/index.brf','admin/index.cfm',
'admin/index.cgi','admin/index.html','admin/index.js','admin/index.php','administer/',
'administer/ LiveUser_Admin/','administr8/','administr8.','administr8.asp','administr8.%EXT%',
'administr8.html','administr8.php','administracao/','administrador/','administratie/',
'administration/','administration.','administration.%EXT%','administration.html','administration.php','administrator/','administrator.',
'administrator/account.','administrator/account.asp','administrator/account.brf',
'administrator/account.cfm','administrator/account.cgi','administrator/account.%EXT%',
'administrator/account.html','administrator/account.js','administrator/account.php',
'administratoraccounts/','administrator.asp','administrator.brf','administrator.cfm',
'administrator.cgi','administrator.%EXT%','administrator.html','administrator/index.asp',
'administrator/index.brf','administrator/index.cfm','administrator/index.cgi',
'administrator/index.html','administrator/index.js','administrator/index.php','administrator.js',
'administrator/login.','administratorlogin/','administratorlogin.','administrator/login.asp',
'administratorlogin.asp','administrator/login.brf','administratorlogin.brf','administrator/login.cfm',
'administratorlogin.cfm','administrator/login.cgi','administratorlogin.cgi',
'administrator/login.%EXT%','administratorlogin.%EXT%','administrator/login.html',
'administrator/login.js','administratorlogin.js','administrator/login.php',
'administratorlogin.php','administrator.php','administrator.php/','administrators/','administrators.',
'administrators.%EXT%','administrivia/','administrivia/ Database_Administration/ WebAdmin/',
'adminitem/','adminitem.','adminitem.%EXT%','adminitems/','adminitems.','adminitems.%EXT%',
'admin.js','admin_login.','admin/login.','adminlogin.','adminLogin/','admin_login.asp','admin-login.asp','admin/login.asp','adminLogin.asp','admin_login.brf','admin-login.brf','admin/login.brf',
'adminLogin.brf','admin_login.cfm','admin-login.cfm','admin/login.cfm','adminLogin.cfm',
'admin_login.cgi','admin-login.cgi','admin/login.cgi','adminLogin.cgi','admin_login.%EXT%',
'admin-login.%EXT%','admin/login.%EXT%','adminlogin.%EXT%','admin/login.htm','admin_login.html',
'admin-login.html','admin/login.html','adminLogin.html','ADMIN/login.html','admin_login.js',
'admin-login.js','admin/login.js','adminLogin.js','admin_login.php','admin-login.php','admin/login.php','adminLogin.php','ADMIN/login.php','adminpanel/','adminpanel.','adminpanel.asp',
'adminpanel.brf','adminpanel.cfm','adminpanel.cgi','adminpanel.%EXT%','adminpanel.html',
'adminpanel.js','adminpanel.php','adminpanel/ PSUser/' ,'admin.php','adminpro/',
'adminpro/ Lotus_Domino_Admin/','admins','admins/','admins.','admins.asp','admins.%EXT%',
'admins.html','adminsite/','admins.php','AdminTools','adm.js','admloginuser.asp','admloginuser.brf',
'admloginuser.cfm','admloginuser.cgi','admloginuser.js','admloginuser.php','admon/','ADMON/',
'adm.php','affiliate.','affiliate.asp','affiliate.brf','affiliate.cfm','affiliate.cgi',
'affiliate.%EXT%','affiliate.js','affiliate.php','auth.','authadmin.','authadmin.%EXT%',
'authenticate.','authenticate.%EXT%','authentication.','authentication.%EXT%','auth.%EXT%',
'authuser.','authuser.%EXT%','autologin/','autologin.','autologin.%EXT%','banneradmin/','bb-admin/',
'bbadmin/','bb-admin/admin.','bb-admin/admin.asp','bb-admin/admin.brf','bb-admin/admin.cfm',
'bb-admin/admin.cgi','bb-admin/admin.%EXT%','bb-admin/admin.html','bb-admin/admin.js','bb-admin/admin.php','bb-admin/index.asp','bb-admin/index.brf','bb-admin/index.cfm','bb-admin/index.cgi',
'bb-admin/index.html','bb-admin/index.js','bb-admin/index.php','bb-admin/login.','bb-admin/login.asp',
'bb-admin/login.brf','bb-admin/login.cfm','bb-admin/login.cgi','bb-admin/login.%EXT%','bb-admin/login.html','bb-admin/login.js','bb-admin/login.php','bigadmin/','blogindex/','blog/wp-login.',
'blog/wp-login.%EXT%','cadmins/','ccms/','ccms/index.php','ccms/login.php','ccp14admin/','cgi-bin/login','cgi-bin/login%EXT%','check.','checkadmin.','checkadmin.%EXT%','check.%EXT%','checklogin.',
'checklogin.%EXT%','checkuser.','checkuser.%EXT%','cms/','cmsadmin/','cmsadmin.','cmsadmin.%EXT%',
'cmsadmin/ SysAdmin2/' ,'config/','configuration/','configure/','control/','control.','controle/',
'control.%EXT%','controlpanel','controlpanel/','controlpanel.','controlpanel.asp','controlpanel.brf',
'controlpanel.cfm','controlpanel.cgi','controlpanel.%EXT%','controlpanel.html','controlpanel.js',
'controlpanel.php','cp','cp/','cp.','cpanel','cpanel/','cPanel/','cpanel_file/','cp.asp','cp.brf',
'cp.cfm','cp.cgi','cp.%EXT%','cp.html','cp.js','cp.php','customer_login/','customer_login/ UserLogin/','database_administration/','Database_Administration/','directadmin/','dir-login/',
'donos/','edit/','emberadmin/','entrar','entrar/','entrar.html','entrar.php','ezsqliteadmin/',
'fileadmin/','fileadmin.','fileadmin.asp','fileadmin.%EXT%','fileadmin.html','fileadmin.php',
'formslogin/','funcoes/','globes_admin/','home.asp','home.brf','home.cfm','home.cgi','home.html',
'home.js','home.php','hpwebjetadmin/','Indy_admin/','instadmin/','irc-macadmin/','isadmin.',
'isadmin.%EXT%','key/','kpanel/','letmein/','letmein.','letmein.%EXT%','LiveUser_Admin/','logar/',
'login','log_in/','log_in.','log-in/','log-in.','login' ,'login/','login.','login1','login1/',
'login1%EXT%','login_admin','login_admin/','login_admin%EXT%','login.asp','login.brf','login.cfm',
'login.cgi','login_db/','loginerror/','log_in.%EXT%','log-in.%EXT%','login.%EXT%','login%EXT%',
'loginflat/','login.htm','login.html','login.js','loginok/','login_out','login_out/','login_out%EXT%',
'login.php','login-redirect/','login-redirect/ sub-login/ ','loginsave/','loginsuper','loginsuper/',
'loginsuper%EXT%','login-us/','login_user','loginuser/','login_user%EXT%','loginusuarios/',
'logo_sysadmin/','logout','logout/','logout%EXT%','Lotus_Domino_Admin/','macadmin/','maintenance/',
'manage/','manage.','manage.%EXT%','management/','management.','management.%EXT%',
'manager/','manager.','manager.%EXT%','manuallogin/','member/','member.','memberadmin/',
'memberadmin.','memberadmin.asp','memberadmin.brf','memberadmin.cfm','memberadmin.cgi',
'memberadmin.%EXT%','memberadmin.js','memberadmin.php','member.%EXT%','members/','members.',
'members.%EXT%','membros/','memlogin/','meta_login/','modcp','modcp/','modelsearch/admin.asp',
'modelsearch/admin.brf','modelsearch/admin.cfm','modelsearch/admin.cgi','modelsearch/admin.html',
'modelsearch/admin.js','modelsearch/admin.php','modelsearch/index.asp','modelsearch/index.brf',
'modelsearch/index.cfm','modelsearch/index.cgi','modelsearch/index.html','modelsearch/index.js',
'modelsearch/index.php','modelsearch/login.','modelsearch/login.asp','modelsearch/login.brf',
'modelsearch/login.cfm','modelsearch/login.cgi','modelsearch/login.%EXT%','modelsearch/login.html',
'modelsearch/login.js','modelsearch/login.php','moderator/','moderator.','moderator/admin.',
'moderator/admin. 0admin/ 0manager/' ,'moderator/admin.asp','moderator/admin.brf','moderator/admin.cfm','moderator/admin.cgi','moderator/admin.%EXT%','moderator/admin.html','moderator/admin.js',
'moderator/admin.php','moderator.asp','moderator.brf','moderator.cfm','moderator.cgi','moderatorcp',
'moderator.%EXT%','moderator.html','moderator.js','moderator/login.','moderator/login.asp',
'moderator/login.brf','moderator/login.cfm','moderator/login.cgi','moderator/login.%EXT%',
'moderator/login.html','moderator/login.js','moderator/login.php','moderator.php','moderator.php/',
'modules/admin/','myadmin/','navSiteAdmin/','net/','newsadmin/','not/','noticias/',
'nsw/admin/login.brf','nsw/admin/login.cfm','nsw/admin/login.cgi','nsw/admin/login.js',
'nsw/admin/login.php','openvpnadmin/','pages/admin/','pages/admin/admin-login.',
'pages/admin/admin-login.asp','pages/admin/admin-login.brf','pages/admin/admin-login.cfm',
'pages/admin/admin-login.cgi','pages/admin/admin-login.%EXT%','pages/admin/admin-login.html',
'pages/admin/admin-login.js','pages/admin/admin-login.php','painel/','paineldecontrole/',
'panel/','panel.','panel-administracion/','panel-administracion/admin.asp','panel-administracion/admin.brf','panel-administracion/admin.cfm','panel-administracion/admin.cgi','panel-administracion/admin.html','panel-administracion/admin.js','panel-administracion/admin.php',
'panel-administracion/index.asp','panel-administracion/index.brf','panel-administracion/index.cfm',
'panel-administracion/index.cgi','panel-administracion/index.html','panel-administracion/index.js',
'panel-administracion/index.php','panel-administracion/login.','panel-administracion/login.asp',
'panel-administracion/login.brf','panel-administracion/login.cfm','panel-administracion/login.cgi',
'panel-administracion/login.%EXT%','panel-administracion/login.html','panel-administracion/login.js',
'panel-administracion/login.php','panelc/','paneldecontrol/','panel.%EXT%','pc/','pdc/','pgadmin/',
'php/','phpldapadmin/','phpmyadmin/','phppgadmin/','phpSQLiteAdmin/','platz_login/','power_user/',
'processlogin.','processlogin.%EXT%','project-admins/','PSUser/','pureadmin/','radmind/','radmind-1/',
'radmind-1/ Super-Admin/ AdminTools/','rcjakar/admin/login.brf','rcjakar/admin/login.cfm','rcjakar/admin/login.cgi',
'rcjakar/admin/login.js','rcjakar/admin/login.php','rcLogin/','registration/','relogin.','relogin.%EXT%','relogin.htm','relogin.html','relogin.php','root/','saff/','secret/','secrets/','secure/',
'security/','senha/','senhas/','server/','Server/','Server.','ServerAdministrator/','server_admin_small/',
'Server.asp','Server.%EXT%','Server.html','Server.php','sff/','showlogin/','sign_in/','sign_in.',
'sign-in/','sign-in.','signin/','signin.','sign_in.%EXT%','sign-in.%EXT%','signin.%EXT%','simpleLogin/','sistema/','site/','siteadmin/','siteadmin.','siteadmin.%EXT%','siteadmin/index.asp','siteadmin/index.brf','siteadmin/index.cfm','siteadmin/index.cgi','siteadmin/index.js',
'siteadmin/index.php','siteadmin/login.asp','siteadmin/login.brf','siteadmin/login.cfm','siteadmin/login.cgi',
'siteadmin/login.html','siteadmin/login.js','siteadmin/login.php','smblogin/','sql-admin/','sshadmin/','ss_vms_admin_sm/','staradmin/','staradmin/ ServerAdministrator/ SysAdmin/',
'sub-login/','super','super1','super1/','super1%EXT%','Super-Admin/','super%EXT%','super_index',
'super_index%EXT%','super_login','super_login%EXT%','superman','superman/','supermanager',
'supermanager%EXT%','superman%EXT%','superuser','superuser/','superuser.','superuser.%EXT%',
'superuser%EXT%','supervise/','supervise/Login','supervise/Login%EXT%','supervise/Login super',
'supervisor/','support_login/','sysadm/','sysadm.','sysadm.%EXT%','sys-admin/','sysadmin/','sysadmin.',
'SysAdmin/','SysAdmin2/','sysadmin.asp','sysadmin.%EXT%','sysadmin.html','sysadmin.php','sysadmins/',
'system_administration/','system-administration/','typo3/','ur-admin/','ur-admin.','ur-admin.asp',
'ur-admin.%EXT%','ur-admin.html','ur-admin.php','ur-admin. Server.' ,'ur-admin/ Server.php Server.html Server.asp Server/','user/','user.','user/admin.','useradmin/','user/admin.%EXT%',
'user.asp','user.brf','user.cfm','user.cgi','user.%EXT%','user.html','user.js','userlogin/',
'userlogin.','UserLogin/','userlogin.%EXT%','user.php','users/','users.','users/admin.',
'users/admin.%EXT%','users.%EXT%','usr/','usuario/','usuarios/','usuarios/login.brf',
'usuarios/login.cfm','usuarios/login.cgi','usuarios/login.js','usuarios/login.php','utility_login/',
'uvpanel/','vadmind/','vmailadmin/','vmailadmin/ Indy_admin/','vorod/','vorod.','vorod.%EXT%',
'vorud/','vorud.','vorud.%EXT%','webadmin/','webadmin.','WebAdmin/','webadmin/admin.asp',
'webadmin/admin.brf','webadmin/admin.cfm','webadmin/admin.cgi','webadmin/admin.html',
'webadmin/admin.js','webadmin/admin.php','webadmin.asp','webadmin.brf','webadmin.cfm','webadmin.cgi',
'webadmin.%EXT%','webadmin.html','webadmin/index.asp','webadmin/index.brf','webadmin/index.cfm',
'webadmin/index.cgi','webadmin/index.html','webadmin/index.js','webadmin/index.php','webadmin.js',
'webadmin/login.asp','webadmin/login.brfbrf','webadmin/login.cfm','webadmin/login.cgi',
'webadmin/login.html','webadmin/login.js','webadmin/login.php','webadmin.php','webmaster/',
'webmaster.','webmaster.%EXT%','websvn/','wizmysqladmin/','wp-admin/','wp-login/','wp-login.brf',
'wp-login.cfm','wp-login.cgi','wp-login.js','wp-login.php','wp-login.php/','xlogin/','yonetici.',
'yonetici.asp','yonetici.%EXT%','yonetici.html','yonetici.php','yonetim.','yonetim.asp','yonetim.%EXT%','yonetim.html','yonetim.php','%s/admin/','%s/admin.asp/','%s/admin/admin.asp/',
'%s/admin.aspx/','%s/admin/admin.aspx/','%s/admin.php/','%s/administrator/','%s/login.php',
'%s/admin.php','%s/user/','%s/usuarios/','%s/usuario/','%s/Admin/','%s/cpanel/','%s/phpmyadmin/',
'%s/dashboard','%s/cms/','%s/users/','%s/wp-login.php/','%s/admin/login','%s/auth/login/',
'%s/moderator/','%s/webadmin/','%s/webmaster/','%s/adminarea/','%s/bb-admin/','%s/wp-admin/',
'%s/wp-login/','%s/wp-admin.php','%s/userlogin/','%s/logins/','%s/login.html','%s/adminLogin/',
'%s/admin_area/','%s/panel-administracion/','%s/instadmin/','%s/memberadmin/','%s/administratorlogin/','%s/panel/','%s/forum/admin','%s/adm/','%s/cp/','%s/vue-element-admin',
'%s/admin/cp.php','%s/cp.php','%s/admincontrol/','%s/admincp/','%s/admin/account.php',
'%s/admin/index.php','%s/admin/login.php','%s/admin/admin.php','%s/admin_area/admin.php',
'%s/admin_area/login.php','%s/siteadmin/login.php','%s/siteadmin/index.php','%s/siteadmin/login.html',
'%s/admin/account.html','%s/admin/index.html','%s/admin/login.html','%s/admin/admin.html',
'%s/admin_area/index.php','%s/dashboard.html','%s/dashboard.php','%s/bb-admin/index.php',
'%s/bb-admin/login.php','%s/bb-admin/admin.php','%s/admin/home.php','%s/admin_area/login.html',
'%s/admin_area/index.html','%s/admin/controlpanel.php','%s/admincp/index.asp','%s/admincp/login.asp',
'%s/admincp/index.html','%s/adminpanel.html','%s/webadmin.html','%s/webadmin/index.html',
'%s/webadmin/admin.html','%s/webadmin/login.html','%s/admin/admin_login.html','%s/admin_login.html',
'%s/panel-administracion/login.html','%s/administrator/index.php','%s/administrator/login.php',
'%s/nsw/admin/login.php','%s/webadmin/login.php','%s/admin/admin_login.php','%s/admin_login.php',
'%s/administrator/account.php','%s/administrator.php','%s/admin_area/admin.html','%s/pages/admin/',
'%s/pages/admin/admin-login.php','%s/admin/admin-login.php','%s/admin-login.php','%s/members/',
'%s/bb-admin/index.html','%s/bb-admin/login.html','%s/acceso.php','%s/bb-admin/admin.html',
'%s/admin/home.html','%s/modelsearch/login.php','%s/moderator.php','%s/moderator/login.php',
'%s/moderator/admin.php','%s/account.php','%s/pages/admin/admin-login.html','%s/admin/admin-login.html','%s/admin-login.html','%s/controlpanel.php','%s/admincontrol.php','%s/admin/adminLogin.html','%s/adminLogin.html','%s/home.html','%s/rcjakar/admin/login.php',
'%s/adminarea/index.html','%s/adminarea/admin.html','%s/webadmin.php','%s/webadmin/index.php',
'%s/webadmin/admin.php','%s/admin/controlpanel.html','%s/admin.html','%s/admin/cp.html',
'%s/cp.html','%s/adminpanel.php','%s/moderator.html','%s/administrator/index.html',
'%s/administrator/login.html','%s/user.html','%s/administrator/account.html','%s/administrator.html',
'%s/modelsearch/login.html','%s/moderator/login.html','%s/adminarea/login.html',
'%s/panel-administracion/index.html','%s/panel-administracion/admin.html','%s/modelsearch/index.html',
'%s/modelsearch/admin.html','%s/admincontrol/login.html','%s/adm/index.html','%s/adm.html',
'%s/moderator/admin.html','%s/user.php','%s/account.html','%s/controlpanel.html','%s/admincontrol.html','%s/panel-administracion/login.php','%s/wp-login.php','%s/adminLogin.php',
'%s/admin/adminLogin.php','%s/home.php','%s/adminarea/index.php','%s/adminarea/admin.php',
'%s/adminarea/login.php','%s/panel-administracion/index.php','%s/panel-administracion/admin.php',
'%s/modelsearch/index.php','%s/modelsearch/admin.php','%s/admincontrol/login.php',
'%s/adm/admloginuser.php','%s/admloginuser.php','%s/admin2.php','%s/admin2/login.php',
'%s/admin2/index.php','%s/usuarios/login.php','%s/adm/index.php','%s/adm.php','%s/affiliate.php',
'%s/adm_auth.php','%s/memberadmin.php','%s/administratorlogin.php','%sadmin.','%slogin.','%slogin1.',
'%spanel.','%sadmin1.','%sadmin2.','%sadmin3.','%sadmin4.','%smoderator.','%swebadmin.','%suser.',
'%s/administration/','%s/mag/admin/','%s/joomla/administrator/','%s/manager/','%s/adminpanel/',
'%s/controlpanel/','%s/logon/','%s/auth/','%s/apanel/','%s/a/','%s/acart/','%s/access/','%s/account/',
'%s/achievo/','%s/address/','%s/admins/','%s/0admin/','%s/admin1/','%s/admin2/','%s/admin3/','%s/admin4/','%s/admin5/','%s/_adm_/','%s/_admin_/','%s/_administrator_/','%s/_adm/','%s/_admin/',
'%s/achtung/','%s/_administrator/','%s/AdminWeb/','%s/administration.php','%s/links/login.php',
'%s/cms/_admin/logon.php','%s/typo3/','%s/pma/','%s/cms/login/','%s/access.php','%s/sysadm.php',
'%s/adm2/','%s/include/admin.php','%s/admin/moderator.php','%s/interactive/admin.php','%s/edit.php',
'%s/siteadmin/','%s/hcaadmin.php','%s/svn/','%s/blog/wp-login.php','%s/admin/log.php',
'%s/login/login.php','%s/adminka.php','%s/wholesale-login.php','%s/authorize.php','%s/editor/',
'%s/base/admin/','%s/includes/login.php','%s/site_admin/login.php','%s/statredir/','%s/lists/admin/',
'%s/sec/login.php','%s/bitrix/admin/','%s/admin_tool/','%s/cabinet/','%s/klarnetCMS/',
'%s/debug/rus/autorisation/','%s/cms/admin/','%s/Admin/private/','%s/site/admin/','%s/admen/',
'%s/admin2/index/','%s/db/admin.php','%s/admin/adm.php','%s/admin/admin/','%s/manager/ispmgr/',
'%s/phpMyAdmin/','%s/login.aspx/','%s/admin/login.asp','%s/admin/login.aspx/','%s/moderator/admin.asp/','%s/webadmin.asp/','%s/webadmin/admin.asp/','%s/author/Admin.aspx/',
'%s/admin/userAdmin.aspx/','%s/dbadmin/','%s/AdministratorS/Admin.aspx/','%s/admin/secure/admin.aspx/','%s/bb-admin/admin.asp/','%s/processlogin.php/','%s/0manager/','%s/acceso.asp/',
'%s/acceso.aspx/','%s/account.asp/','%s/account.aspx/','%s/wp-login.asp/','%s/wp-login.aspx/',
'%s/admin_login/','%s/admin-login/','%s/modelsearch/','%s/nsw/','%s/rcjakar/','%s/private.php/',
'%s/_vti_pvt/','%s/_private/','%s/admin1.php','%s/admin2.html','%s/yonetim.php','%s/yonetim.html',
'%s/nedmin/production/login.php','%s/nedmin/production/index.php','%s/yonetici.php','%s/yonetici.html','%s/admin1.asp','%s/admin2.asp','%s/yonetim.asp','%s/yonetici.asp','%s/admin/index.asp',
'%s/admin/home.asp','%s/admin/controlpanel.asp','%s/sysadmin.php','%s/sysadmin.html','%s/sysadmin/',
'%s/ur-admin.asp','%s/ur-admin.php','%s/ur-admin.html','%s/ur-admin/','%s/administr8.php',
'%s/administr8.html','%s/administr8/','%s/admin/acceso.php/','%s/admin/acceso.asp/','%s/admin/acceso.aspx/','%s/admin_area/acceso.php/','%s/admin_area/acceso.asp/','%s/admin_area/acceso.aspx/',
'%s/adminarea/acceso.php/','%s/adminarea/acceso.asp/','%s/adminarea/acceso.aspx/','%s/admincontrol/acceso.php/','%s/admincontrol/acceso.asp/','%s/admincontrol/acceso.aspx/','%s/admincpacceso.php/',
'%s/admincpacceso.asp/','%s/admincpacceso.aspx/','%s/administrator/acceso.php/','%s/administrator/acceso.asp/','%s/administrator/acceso.aspx/','%s/admin_login/acceso.php/','%s/admin_login/acceso.asp/',
'%s/admin_login/acceso.aspx/','%s/adminlogin/acceso.php/','%s/adminlogin/acceso.asp/',
'%s/adminlogin/acceso.aspx/','%s/webadmin/wp-login.php/','%s/webadmin/wp-login.asp/',
'%s/webadmin/wp-login.aspx/','%s/usuario/wp-login.php/','%s/usuario/wp-login.asp/',
'%s/usuario/wp-login.aspx/','%s/admin/webadmin.asp/','%s/admin/webadmin.aspx/','%s/admin/webadmin.php/','%s/webadmin/user.php/','%s/webadmin/user.asp/','%s/webadmin/user.aspx/',
'%s/bb-admin/user.php','%s/bb-admin/user.asp','%s/bb-admin/user.aspx','%s/controlpanel/user.php',
'%s/controlpanel/user.asp','%s/controlpanel/user.aspx','%s/admin-login/user.php','%s/admin-login/user.asp','%s/admin-login/user.aspx','%s/administrator/user.php','%s/administrator/user.asp',
'%s/administrator/user.aspx','%s/admin/user.php','%s/adm/user.php','%s/pages/moderator.php',
'%s/webadmin/moderator.php','%s/users/moderator.php','%s/usuario/user.php/','%s/usuario/user.asp/',
'%s/usuario/user.aspx/','%s/mysql/','%s/myadmin/','%s/sqlmanager/','%s/mysqlmanager/','%s/p/m/a/',
'%s/phpmanager/','%s/php-myadmin/','%s/phpmy-admin/','%s/sqlweb/','%s/websql/','%s/webdb/','%s/mysqladmin/','%s/mysql-admin/','%s/phpmyadmin2/','%s/phpMyAdmin-2/','%s/php-my-admin/',
'%s/phpMyAdmin-2.2.3/','%s/phpMyAdmin-2.2.6/','%s/phpMyAdmin-2.5.1/','%s/phpMyAdmin-2.5.4/',
'%s/phpMyAdmin-2.5.5-rc1/','%s/phpMyAdmin-2.5.5-rc2/','%s/phpMyAdmin-2.5.5/','%s/phpMyAdmin-2.5.5-pl1/','%s/phpMyAdmin-2.5.6-rc1/','%s/phpMyAdmin-2.5.6-rc2/','%s/phpMyAdmin-2.5.6/',
'%s/phpMyAdmin-2.5.7/','%s/phpMyAdmin-2.5.7-pl1/','%s/phpMyAdmin-2.6.0-alpha/',
'%s/phpMyAdmin-2.6.0-alpha2/','%s/phpMyAdmin-2.6.0-beta1/','%s/phpMyAdmin-2.6.0-beta2/',
'%s/phpMyAdmin-2.6.0-rc1/','%s/phpMyAdmin-2.6.0-rc2/','%s/phpMyAdmin-2.6.0-rc3/',
'%s/phpMyAdmin-2.6.0/','%s/phpMyAdmin-2.6.0-pl1/','%s/phpMyAdmin-2.6.0-pl2/','%s/phpMyAdmin-2.6.0-pl3/','%s/phpMyAdmin-2.6.1-rc1/','%s/phpMyAdmin-2.6.1-rc2/','%s/phpMyAdmin-2.6.1/',
'%s/phpMyAdmin-2.6.1-pl1/','%s/phpMyAdmin-2.6.1-pl2/','%s/phpMyAdmin-2.6.1-pl3/',
'%s/phpMyAdmin-2.6.2-rc1/','%s/phpMyAdmin-2.6.2-beta1/','%s/phpMyAdmin-2.6.2/','%s/phpMyAdmin-2.6.2-pl1/','%s/phpMyAdmin-2.6.3/','%s/phpMyAdmin-2.6.3-rc1/','%s/phpMyAdmin-2.6.3-pl1/',
'%s/phpMyAdmin-2.6.4-rc1/','%s/phpMyAdmin-2.6.4-pl1/','%s/phpMyAdmin-2.6.4-pl2/','%s/phpMyAdmin-2.6.4-pl3/','%s/phpMyAdmin-2.6.4-pl4/','%s/phpMyAdmin-2.6.4/','%s/phpMyAdmin-2.7.0-beta1/',
'%s/phpMyAdmin-2.7.0-rc1/','%s/phpMyAdmin-2.7.0-pl1/','%s/phpMyAdmin-2.7.0-pl2/','%s/phpMyAdmin-2.7.0/','%s/phpMyAdmin-2.8.0-beta1/','%s/phpMyAdmin-2.8.0-rc2/','%s/phpMyAdmin-2.8.0/',
'%s/phpMyAdmin-2.8.0.1/','%s/phpMyAdmin-2.8.0.2/','%s/phpMyAdmin-2.8.0.3/','%s/phpMyAdmin-2.8.0.4/',
'%s/phpMyAdmin-2.8.1-rc1/','%s/phpMyAdmin-2.8.1/','%s/phpMyAdmin-2.8.2/','%s/pma2005/',
'%s/administratie/','%s/admins.php','%s/useradmin/','%s/sysadmins/','%s/system-administration/',
'%s/administrators/','%s/pgadmin/','%s/directadmin/','%s/sql-admin/','%s/newsadmin/','%s/adminpro/',
'%s/staradmin/','%s/ServerAdministrator/','%s/SysAdmin/','%s/administer/','%s/LiveUser_Admin/',
'%s/sys-admin/','%s/autologin/','%s/support_login/','%s/memlogin/','%s/login-redirect/','%s/sub-login/','%s/login1/','%s/dir-login/','%s/login_db/','%s/xlogin/','%s/smblogin/','%s/customer_login/',
'%s/UserLogin/','%s/acct_login/','%s/bigadmin/','%s/project-admins/','%s/phppgadmin/','%s/pureadmin/',
'%s/bbadmin/','%s/administratoraccounts/','%s/AdminTools/','%s/server/','%s/database_administration/',
'%s/power_user/','%s/system_administration/','%s/adminitem/','%s/sysadm/','%s/control/','%s/accounts/','%s/management/','%s/phpSQLiteAdmin/','%s/showlogin/','%s/0admin/login.asp',
'%s/0manager/admin.asp','%s/admin/sendfile.asp','%s/admin/sndfile.asp','%s/admin/upfile.asp',
'%s/admin/upload.asp','%s/admin/uploadfaceok.asp','%s/admin/uploads.asp','%s/admin/uppic.asp',
'%s/adminadmin/','%s/adminindex/','%s/count_admin','%s/default_admin','%s/index/admin','%s/acesso/',
'%s/adimin/','%s/adiministrador/','%s/adm/admin/','%s/admin4_account/','%s/admin4_colon/',
'%s/admin/adm/','%s/administracao/','%s/banneradmin/','%s/blogindex/','%s/cadmins/','%s/ccp14admin/',
'%s/cmsadmin/','%s/config/','%s/controle/','%s/cpanel_file/','%s/donos/','%s/edit/','%s/entrar',
'%s/entrar.html','%s/entrar.php','%s/ezsqliteadmin/','%s/formslogin/','%s/funcoes/','%s/globes_admin/','%s/hpwebjetadmin/','%s/Indy_admin/','%s/irc-macadmin/','%s/key/','%s/logar/',
'%s/login/','%s/loginflat/','%s/login-us/','%s/loginuser/','%s/loginusuarios/','%s/logo_sysadmin/',
'%s/logout/','%s/Lotus_Domino_Admin/','%s/macadmin/','%s/manuallogin/','%s/membros/','%s/meta_login/',
'%s/navSiteAdmin/','%s/net/','%s/not/','%s/openvpnadmin/','%s/painel/','%s/paineldecontrole/',
'%s/pc/','%s/pdc/','%s/php/','%s/phpldapadmin/','%s/platz_login/','%s/radmind/','%s/radmind-1/',
'%s/rcLogin/','%s/saff/','%s/senha/','%s/senhas/','%s/server_admin_small/','%s/sff/',
'%s/simpleLogin/','%s/sistema/','%s/sshadmin/','%s/ss_vms_admin_sm/','%s/Super-Admin/','%s/SysAdmin2/','%s/userlogin/','%s/utility_login/','%s/vadmind/','%s/vmailadmin/','%s/wizmysqladmin/',
'%s/ccms/','%s/ccms/login.php','%s/ccms/index.php',

    );

    echo "
-----------------------------------------------------------------------------------------------------------------------------
  
███╗░░░███╗░█████╗░░██████╗░██████╗  ██████╗░██╗██████╗░███████╗░█████╗░████████╗░█████╗░██████╗░██╗░░░██╗
████╗░████║██╔══██╗██╔════╝██╔════╝  ██╔══██╗██║██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗╚██╗░██╔╝
██╔████╔██║███████║╚█████╗░╚█████╗░  ██║░░██║██║██████╔╝█████╗░░██║░░╚═╝░░░██║░░░██║░░██║██████╔╝░╚████╔╝░
██║╚██╔╝██║██╔══██║░╚═══██╗░╚═══██╗  ██║░░██║██║██╔══██╗██╔══╝░░██║░░██╗░░░██║░░░██║░░██║██╔══██╗░░╚██╔╝░░
██║░╚═╝░██║██║░░██║██████╔╝██████╔╝  ██████╔╝██║██║░░██║███████╗╚█████╔╝░░░██║░░░╚█████╔╝██║░░██║░░░██║░░░
╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═════╝░╚═════╝░  ╚═════╝░╚═╝╚═╝░░╚═╝╚══════╝░╚════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░

░██████╗░█████╗░░█████╗░███╗░░██╗███╗░░██╗███████╗██████╗░
██╔════╝██╔══██╗██╔══██╗████╗░██║████╗░██║██╔════╝██╔══██╗
╚█████╗░██║░░╚═╝███████║██╔██╗██║██╔██╗██║█████╗░░██████╔╝
░╚═══██╗██║░░██╗██╔══██║██║╚████║██║╚████║██╔══╝░░██╔══██╗     𝗖𝗼𝗱𝗲𝗱 𝗯𝘆 𝗟𝟰𝗭𝗬𝗚𝟯𝟯𝗞 
██████╔╝╚█████╔╝██║░░██║██║░╚███║██║░╚███║███████╗██║░░██║
╚═════╝░░╚════╝░╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚══╝╚══════╝╚═╝░░╚═╝  

Greetings:  Devil's Pride Hacker|Security Exploiter|Pinoy Cyber DDOS|Razor Elite Force Team|SQLi & Pentest Training Ground
                           
-----------------------------------------------------------------------------------------------------------------------------
";
    
	echo "[*]The quieter you become, the more you are able to hear\n";
    echo "Target site : ";
    $target = fopen("php://stdin","r"); 
    $url = trim(fgets($target));


    foreach ($wordlist as $key) {
        $domain = $url.'/'.$key;

        $checker = get_headers($domain);

        if (preg_match('/200/', $checker[0])) {
            echo "+===========================================================+\n";
            echo "[*] 200 found  => ".$domain."\n";
            echo "+===========================================================+\n";
        }else{
            echo "[x] 404 not found or 403 access forbidden  => ".$domain."\n";
        }

    }
?>
